---

- name: extract core
  unarchive:
    src: "{{ install_dir }}/jumpserver.tar.gz"
    dest: "{{ install_dir }}"
    copy: no

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
